//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.SINAC.Idiomas {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResOrdenCompra_en_USA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResOrdenCompra_en_USA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Proyecto.SINAC.Idiomas.ResOrdenCompra.en-USA", typeof(ResOrdenCompra_en_USA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult (@) Resident.
        /// </summary>
        internal static string AdultoResidente {
            get {
                return ResourceManager.GetString("AdultoResidente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to the list.
        /// </summary>
        internal static string AgregaLista {
            get {
                return ResourceManager.GetString("AgregaLista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration year.
        /// </summary>
        internal static string AnioVencimiento {
            get {
                return ResourceManager.GetString("AnioVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel purchase.
        /// </summary>
        internal static string CancelarCompra {
            get {
                return ResourceManager.GetString("CancelarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel order.
        /// </summary>
        internal static string CancelarPedido {
            get {
                return ResourceManager.GetString("CancelarPedido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of tickets.
        /// </summary>
        internal static string CantidadEntradas {
            get {
                return ResourceManager.GetString("CantidadEntradas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security code.
        /// </summary>
        internal static string CodigoSeguridad {
            get {
                return ResourceManager.GetString("CodigoSeguridad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        internal static string Compra {
            get {
                return ResourceManager.GetString("Compra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm purchase.
        /// </summary>
        internal static string ConfirmarCompra {
            get {
                return ResourceManager.GetString("ConfirmarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Data.
        /// </summary>
        internal static string DatosPago {
            get {
                return ResourceManager.GetString("DatosPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitor Data.
        /// </summary>
        internal static string DatosVisitantes {
            get {
                return ResourceManager.GetString("DatosVisitantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation date.
        /// </summary>
        internal static string FechaReservacion {
            get {
                return ResourceManager.GetString("FechaReservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photography.
        /// </summary>
        internal static string Fotografia {
            get {
                return ResourceManager.GetString("Fotografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Identificacion {
            get {
                return ResourceManager.GetString("Identificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string Impuesto {
            get {
                return ResourceManager.GetString("Impuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information.
        /// </summary>
        internal static string MasInformacion {
            get {
                return ResourceManager.GetString("MasInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration month.
        /// </summary>
        internal static string MesVencimiento {
            get {
                return ResourceManager.GetString("MesVencimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment currency.
        /// </summary>
        internal static string MonedaPago {
            get {
                return ResourceManager.GetString("MonedaPago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are a child, please put an asterist (*) in the identification.
        /// </summary>
        internal static string Ninio {
            get {
                return ResourceManager.GetString("Ninio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string NombreCompleto {
            get {
                return ResourceManager.GetString("NombreCompleto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park name.
        /// </summary>
        internal static string NombreParque {
            get {
                return ResourceManager.GetString("NombreParque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        internal static string NumeroTarjeta {
            get {
                return ResourceManager.GetString("NumeroTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of residence.
        /// </summary>
        internal static string PaisResidencia {
            get {
                return ResourceManager.GetString("PaisResidencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        internal static string Reservacion {
            get {
                return ResourceManager.GetString("Reservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub total.
        /// </summary>
        internal static string SubTotal {
            get {
                return ResourceManager.GetString("SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind of person.
        /// </summary>
        internal static string TipoPersona {
            get {
                return ResourceManager.GetString("TipoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of admission.
        /// </summary>
        internal static string TiposAdminsion {
            get {
                return ResourceManager.GetString("TiposAdminsion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card type.
        /// </summary>
        internal static string TipoTarjeta {
            get {
                return ResourceManager.GetString("TipoTarjeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate card.
        /// </summary>
        internal static string ValidarTarjeta {
            get {
                return ResourceManager.GetString("ValidarTarjeta", resourceCulture);
            }
        }
    }
}
